### PR TITLE
NCL-5351 - Filter subquery for the same BuildConfigurationAudited.idRev

### PR DESCRIPTION
**Pull request by vibe13**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by vibe13** [comment]
@thescouser89 @jbartece please review. Thanks!

**Comment by vibe13** [comment]
Thanks @thescouser89 foe the review, cool. If you mean the indexes on the tables used by the queries above, yes we already have all the indexes in DB for those. I double checked with a EXPLAIN ANALYZE query on the generated Hibernate sql (linked in the JIRA), which uses only Index scan (good). It's that what you mean? Thanks!

**Comment by thescouser89** [comment]
@vibe13 yup! COOL COOL THEN! As always you already prepared for everything :)

**Comment by vibe13** [comment]
@jbartece ok thanks! I have updated the javadoc now :-)

**Pull request merged**
