### PR TITLE
Fix new atomic builds endpoints not following REST guideliness - 1.4

### PR DESCRIPTION
**Pull request by jbartece**

### CODE REVIEW

**Comment by jbartece** [comment]
@alexcreasy For the endpoint "update-and-get-audited" I let the path the same as it returns different entity than POST /{id}. That would not be great to return different entity based on a query parameter

**Comment by alexcreasy** [comment]
@jbartece +1 to just changing the method on update-and-get-audited, it's more explicit in it's intent than using the query param and, you're right multiple return types for one endpoint is confusing.

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Pull request merged**
