### PR TITLE
[NCL-6068] Log Artifact promotion failure as WARNING

### PR DESCRIPTION
**Pull request by jomrazek**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
Wouldn't the failure to promote an error? I'm curious why you'd like to change it to warning :)

**Comment by jomrazek** [comment]
we might want to have less error logs in openshift for better overview of running service? don't know when or why this was agreed @matejonnet can you answer ^

**Comment by thescouser89** [comment]
:(

**Comment by jomrazek** [comment]
@thescouser89 now @matejonnet  needs to look into it :) we can always revert it

**Pull request merged**
