### PR TITLE
[NCL-4066] Fix target repository paths for deps and built artifacts

### PR DESCRIPTION
**Pull request by pkocandr**

### CODE REVIEW

**Comment by pkocandr** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
Still fighting with that flaky test in our Jenkins instance. Will look at it today.

**Comment by pkocandr** [comment]
Thank you!

**Comment by thescouser89** [comment]
retest this please

**Comment by matejonnet** [comment]
@pkocandr the "api" part should be added where the rest of the path is defined.

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
