### PR TITLE
NCL-2559 Fixes error thrown when clicking save after editing a BuildC…

### PR DESCRIPTION
**Pull request by alexcreasy**
…onfig

### CODE REVIEW

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Pull request merged**
