### PR TITLE
Fixes NCL-3302 / NCL-3303

### PR DESCRIPTION
**Pull request by alexcreasy**
- NCL-3302 Wizard is still navigable after completion
  - NCL-3303 Wizard next button incorrectly labelled on completion

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
