### PR TITLE
NCL-4344 provides the UI mechanism to display a service notification

### PR DESCRIPTION
**Pull request by alexcreasy**
### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
Feel free to merge if there are no more nit picking changes needed lol

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
