### PR TITLE
[NCL-808] Change the one to many parent self relation on build config to a many to many - Web UI

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
@vibe13 would you mind reviewing please?

**Comment by alexcreasy** [comment]
Retest this please

**Comment by vibe13** [comment]
@alexcreasy looks great. 2 minor things: 
1) I would also parametrize the placeholder in https://github.com/project-ncl/pnc/pull/370/files#diff-3eea84ad9786fee0ca08863fef3ebbf8R61, so that we can display the hint correctly for every item (now it's always "Enter product versions..."). 
2) we should also display those additional fields in the details of a BuildConfiguration, and change them when editing.

Other than that, +1 !

**Comment by alexcreasy** [comment]
OK cool thanks I'll get that updated now

**Comment by vibe13** [comment]
@alexcreasy maybe we should also add some basic validation (* for required fields at least?), see Milestone creation page? thanks!

**Comment by alexcreasy** [comment]
Ok sure

**Comment by vibe13** [comment]
retest this please

**Comment by alexcreasy** [comment]
@vibe13 if you wouldn't mind reviewing once again :)

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by vibe13** [comment]
works great, +1 to merge

**Pull request merged**
