### PR TITLE
Updated infiniteSelect from Martin PR: https://github.com/project-ncl…

### PR DESCRIPTION
**Pull request by vibe13**
…/pnc/pull/744

### CODE REVIEW

**Comment by vibe13** [comment]
@alexcreasy  please review

**Comment by vibe13** [comment]
retest this please

**Comment by alexcreasy** [comment]
+1 for merging

**Comment by vibe13** [comment]
@alexcreasy DO NOT MERGE, fixing validation issues

**Comment by alexcreasy** [comment]
@vibe13 Sure, I'l leave it to you! I've looked at the code and it all looks good in general, I haven't tested it fully though!

**Comment by vibe13** [comment]
@alexcreasy  ok updated and fixed the validation errors! :)

**Pull request merged**
