### PR TITLE
NCL-1296 BuildConfiguration edits are lost when I'm not logged in

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
@alexcreasy  Jesus I thought you had a public holiday!

**Comment by alexcreasy** [comment]
@thescouser89 yeah, wonders of modern technology, I merged from my phone whilst watching TV :P Hopefully now it'll be fully built for more testing this morning!

**Pull request merged**
