### PR TITLE
Update to EAP7.3.

### PR DESCRIPTION
**Pull request by matejonnet**

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by matejonnet** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
