### PR TITLE
[NCL-5638]: Remove Product.productCode and Product.pgmSystemName

### PR DESCRIPTION
**Pull request by jbartece**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by vibe13** [comment]
@jbartece looks good to me, but I believe there are some parts to be fixed on UI as well:
producst_1
producst_2

**Comment by jbartece** [comment]
@vibe13 There is a separate ticket for UI and CLI

**Comment by jbartece** [comment]
@DnsZhou Hi. Once you have a fix for the UI add it to this PR, so that we can merge it together.

**Comment by jbartece** [comment]
@janinko Ah, my bad. Thanks for reminding me.

**Comment by jbartece** [comment]
UI fixes are done in the PR #2967

**Pull request merged**
