### PR TITLE
NCL-2120 Fix tooltips, by upgrading core UI dependencies to latest.

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
@matedo1 Hey martin, finally the PR  is ready :) If this passes CI I'll merge and we can get to work on fully testing once it's deployed.

**Comment by matedo1** [comment]
@alexcreasy Hi Alex, thanks for letting me know, I'll keep eyes on it

**Comment by alexcreasy** [comment]
@matedo1 OK think this is finally fixed :) Basically, I've added a direct dependency on bootstrap-touchspin to an unreleased commit that has a fix with added main properties to bower.json. I've also put a resolution override to this version so bower always picks it. While being hacky this allows us to use the latest patternfly.

**Comment by alexcreasy** [comment]
Retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by alexcreasy** [comment]
woot

**Comment by alexcreasy** [comment]
@thescouser89 I don't know what magic sauce you used, but thanks!

**Pull request merged**
