### PR TITLE
Catch all communication errors in the rest-client

### PR DESCRIPTION
**Pull request by jbartece**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by jbartece** [comment]
@thescouser89 @jomrazek @janinko FYI

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by thescouser89** [comment]
LGTM

**Pull request merged**
