### PR TITLE
Ncl 1436 - ProductVersion, Project and Environment selection directives improvement

### PR DESCRIPTION
**Pull request by vibe13**
This PR aims to optimize the selection of Projects, Environments and ProductVersions.
Projects and Environments once selected, are displayed similarly to dependencies (input field is hidden, and element can be removed by clicking the X icon). This to avoid the case where a user selects an element and then cancels some text from the input field (which is still modifiable), having an element selected for creation while seeing in the UI its partial name.
A new directive is used for the selection of productVersion, avoiding much boilerplate code, and ugly nested select elements.

product_version_selection
project_environments_selection

@alexcreasy Could you please review? Thanks!

### CODE REVIEW

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by alexcreasy** [comment]
@vibe13  there's one issue with the project selection in Create Build Configuration, that's if I type say fab but don't select fabric 8, then move to another field the form field doesn't go red and give a help message, wdyt?

**Comment by alexcreasy** [comment]
Everything else gets a +1 for merging

**Comment by vibe13** [comment]
@alexcreasy fixed the validation

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
@alexcreasy hey alex! I would like to merge this one today, will you have a chance to take a look at this? thanks!

**Comment by vibe13** [comment]
retest this please

**Pull request merged**
