### PR TITLE
Use config parameters instead of PullingMonitor timeout constants.

### PR DESCRIPTION
**Pull request by jsenko**

### CODE REVIEW

**Comment by jsenko** [comment]
Bug in Jenkins. TODO retest later.

**Comment by jsenko** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by thescouser89** [comment]
I will close this PR since it's in an unmergeable state. While this PR does add functionality to set the default wait time for pod to start, we just increased the timeout to a default of 300 seconds and in that ~ 1 year since the change has been done we've never had a need to configure it to less/more seconds.

So while I think this PR is very useful, we didn't have any actual need for it. We'll reconsider the changes if we have a need for this in the future :)

**Comment by thescouser89** [comment]
After talking with @matejonnet , we're going to try to re-merge this PR into PNC master after fixing the merge conflicts :) I will cherry-pick the commit and work on the conflicts.

**Pull request closed without merging**
