### PR TITLE
Several UI fixes and improvements

### PR DESCRIPTION
**Pull request by matedo1**

### CODE REVIEW

**Comment by pslegr** [comment]
This PR doesn't have corresponding issue target release 0.8 - please discuss with @jbartece about pulling this in.

**Comment by matedo1** [comment]
Hi @pslegr , I've been already asked by Alex to raise this PR also for v0.8 here https://github.com/project-ncl/pnc/pull/909

**Comment by jbartece** [comment]
@matedo1 Feel free to merge it to the 0.8 branch as that are minor UI fixes

**Comment by pslegr** [comment]
@matedo1 Please update all JIRA's, which were fixed with this PR and update the "Fix version" field to say 0.8 - to make sure this will be tracked with 0.8 release, thx !

**Comment by matedo1** [comment]
@pslegr All JIRA's are updated and closed, thanks

**Pull request merged**
