### PR TITLE
Extract temporary as a separate flag in TargetRepository

### PR DESCRIPTION
**Pull request by pkocandr**
The flag was merged into repository type, which does not make much sense
and made the code more complicated, since 2 values had to be checked for
a single repository type.

### CODE REVIEW

**Comment by matedo1** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
Ugh, now I've noticed that the first commit in the branch got lost when rebasing on master :-/ Working on a fix.

**Pull request merged**
