### PR TITLE
0.3 UI

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
test this please

**Comment by alexcreasy** [comment]
Test this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by slaskawi** [comment]
on last chance

**Comment by slaskawi** [comment]
retest this please

**Comment by slaskawi** [comment]
I think the failure might be fixed by https://github.com/project-ncl/pnc/pull/177

**Comment by jbartece** [comment]
@slaskawi Why do you think that this PR is connected to #177 ?

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
AVADA KEDAVRA!

**Comment by slaskawi** [comment]
Turned off node slave 2, let's see now

**Comment by slaskawi** [comment]
retest this please

**Comment by alexcreasy** [comment]
dammit you win this time bot!

**Comment by alexcreasy** [comment]
ahhh well done.... BOTULUS REPAIRO!

**Pull request merged**
