### PR TITLE
Atomic builds

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by janinko** [comment]
@matejonnet There is no buildType in the audited entity, so I had to get it this way: https://github.com/project-ncl/pnc/pull/2124/files#diff-c0a65b581338e0155f5c0ad6a8c7edd3R90
Is that ok? Should buildType be audited?

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by matejonnet** [comment]
Yes, a BuildType have to be audited too.

**Pull request merged**
