### PR TITLE
NCL-1893 UI for alignment reports: show already built artifacts in a project

### PR DESCRIPTION
**Pull request by matedo1**

### CODE REVIEW

**Comment by alexcreasy** [comment]
@matedo1 Sorry for the delay, I'm happy for this to be merged, can you fix the merge conflicts when you get a chance?

**Comment by matedo1** [comment]
@alexcreasy Hi, I fixed conflicts now + updated `ui/app/common/restclient/services/ReportDAO.js` to use new config version, feel free to merge it if it looks good for you, thanks!

**Comment by alexcreasy** [comment]
Cool, thanks! +1 for merging after CI build.

**Comment by matedo1** [comment]
retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by alexcreasy** [comment]
Merging

**Pull request merged**
