### PR TITLE
Cannot update dependencies of BuildConfig

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by pgier** [comment]
The current behaviour is intentional, dependencies of a build config can be set using add/remove individual dependency instead of trying to update them all at once.

**Comment by vibe13** [comment]
retest this please

**Comment by pgier** [comment]
I created PR #797 to resolve NCL-1597.  
I think the dependency validation in this PR a nice extra step.

**Comment by pgier** [comment]
I'll include the validiation changes in #797

**Pull request closed without merging**
