### PR TITLE
NCL-607: Remove Column Browser

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Test this please

**Comment by alexcreasy** [comment]
Test this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Waiting for code review from: @vibe13

**Comment by vibe13** [comment]
@alexcreasy Hi Alex looks good and much cleaner. Ok for merging, then we will fill the gaps between ProductVersions and BuildConfigurationSet, and from Project to BuildConfiguration and BuildConfigurationSet. Also a breadcrumb is needed and some alignments on the pages.
+1

**Pull request merged**
