### PR TITLE
NCL-1749 Only running builds (Group Builds) are displayed

### PR DESCRIPTION
**Pull request by matedo1**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
+1 for merging after CI pass, @matedo1 can you raise a PR against 0.8 for this as well please? I think this is definitely worth including.

**Comment by pgier** [comment]
retest this please

**Comment by pgier** [comment]
retest this please

**Comment by alexcreasy** [comment]
Merging

**Pull request merged**
