### PR TITLE
Ncl 2401 projects endpoint

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by alexcreasy** [comment]
Dustin on it like sonic!

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Pull request merged**
