### PR TITLE
[v1.7] NCL-4705, NCL-4434, NCL-4435 Backport artifact views to v1.7

### PR DESCRIPTION
**Pull request by alexcreasy**
(cherry picked from commit ab19a18dbaa03c3e2c69f869231edd1d5d47acf8)
Signed-off-by: Alex Creasy <acreasy@redhat.com>

### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by alexcreasy** [comment]
Test this please

**Comment by alexcreasy** [comment]
Still got some more ES2015 features to revert!

**Pull request merged**
