### PR TITLE
NCL-802 NCL-817 Product Milestones DB change

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by vibe13** [comment]
test this please

**Comment by vibe13** [comment]
test this please

**Comment by vibe13** [comment]
@pgier @alexcreasy @rnc  mind to review? this fixes also NCL-817

**Comment by pgier** [comment]
I kind of prefer that "planned_starting_date" is just called "starting_date".  I don't think we have any reason to differentiate between planned and actual starting state.  We only care about the date we actually started working on the milestone.

**Comment by vibe13** [comment]
@pgier ok thanks will change it

**Comment by slaskawi** [comment]
retest this please

**Comment by rnc** [comment]
I suppose if we were to have planned start date that might differ from our actual start date - which PM are more interested in. If (in future) we could provide that capability where they can compare the start/end dates compared with their planning that would be sufficient.

**Comment by alexcreasy** [comment]
Yes this works for me!

**Pull request merged**
