### PR TITLE
NCL-4934 GroupConfiguration endpoint should have plural base path to …

### PR DESCRIPTION
**Pull request by alexcreasy**
…match others and general REST best practices.

### CODE REVIEW

**Comment by alexcreasy** [comment]
@janinko could you just check I don't need to update this URL anywhere else?

**Comment by alexcreasy** [comment]
This idiot, didn't update the tests presumably lol

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by janinko** [comment]
Retest this please

1 similar comment

**Comment by alexcreasy** [comment]
Retest this please

**Comment by janinko** [comment]
stupid jenkins

**Pull request merged**
