### PR TITLE
[NCL-4395] Partial implementation of BpmEndpoint

### PR DESCRIPTION
**Pull request by thescouser89**
The 'notify' part is not yet implemented; waiting for NCL-4253.

The 'get all' and 'get specific' bpm tasks are implemented.

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
@janinko @michalovjan Could you give this a review?

**Comment by thescouser89** [comment]
@janinko @michalovjan Could you give this a review?

**Comment by thescouser89** [comment]
@janinko @michalovjan Could you give this a review?

Also: is it correct to assume that BPMTask is the DTO of BpmTask?

**Comment by michalovjan** [comment]
That I personally don't know I think Matej some time ago mentioned BpmTasks... I don't remember. @janinko may know more.

Either way I think using BpmTasks directly is something we want to avoid as it introduces a dependency to bpm module in rest-new(rest-api maybe too) that should stay on the facade.

**Comment by thescouser89** [comment]
@janinko  @michalovjan please give it a review! If merged, I'll use it as the base for NCL-4912 also (BuildTaskEndpoint)

**Pull request closed without merging**
