### PR TITLE
Ncl 1838 - BuildConfig details page should use the single endpoint for running/archived builds

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by vibe13** [comment]
@alexcreasy This would be the initial change to use the single endpoint, then optimizations of the refresh can be applied (also based on your previous work)

**Comment by vibe13** [comment]
@alexcreasy Hi Alex, mind to take a look? Thanks!

**Comment by alexcreasy** [comment]
@vibe13 looks good to me, nice amount of red on the diff :)

**Comment by vibe13** [comment]
@alexcreasy  thanks!

**Pull request merged**
