### PR TITLE
NCL-665 - Implement the PNC UI features for authenticated users

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Test this please

**Comment by alexcreasy** [comment]
@pslegr would you mind reviewing this PR please?

**Comment by pslegr** [comment]
@alexcreasy ok, let me review

**Comment by pslegr** [comment]
Looks good to me ! the logout back to login page is also good idea ! go ahead and merge

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
@pslegr great thanks!

**Pull request merged**
