### PR TITLE
Add docs and configuration for postgres

### PR DESCRIPTION
**Pull request by pgier**
Config for running the integration tests against postgresql

### CODE REVIEW

**Comment by slaskawi** [comment]
Testing CI, please ignore my further comments

**Comment by slaskawi** [comment]
retest this please

**Comment by slaskawi** [comment]
retest this please

**Comment by pgier** [comment]
The reason for the Jenkins build failure is because of the changes to the profile settings.  The current Jenkins job assumes that when the eap profile is activated, the wildfly profile will automatically be deactivated.  This is no longer the case.  The Maven command should be changed from:

    mvn clean install -Peap640 ...

to

    mvn clean install -Deap ..

**Comment by slaskawi** [comment]
retest this please

**Comment by pgier** [comment]
retest this please

**Pull request merged**
