### PR TITLE
[NCL-8275] Allow page size of 0

### PR DESCRIPTION
**Pull request by patrikk0123**
### Checklist:

* [x] Have you added unit tests for your change?

### CODE REVIEW

**Review by janinko — CHANGES_REQUESTED** [review]
Please add tests that test that the page size 0 works as expected.

**Comment by patrikk0123** [comment]
retest this please

**Comment by patrikk0123** [comment]
retest this please

**Comment by patrikk0123** [comment]
retest this please

**Review by janinko — APPROVED** [review]

**Pull request merged**
