### PR TITLE
[NCL-4993] Add UserEndpointTest

### PR DESCRIPTION
**Pull request by thescouser89**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [x] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
Missing test for `getCurrentUser` method

**Comment by janinko** [comment]
And please move it to package org.jboss.pnc.integration_new.endpoint.

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
@vibe13 @janinko @jbartece @matejonnet OK to drop the email from the User.java? Do we even use it?

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
This PR makes the email field optional. Cause why not?

**Comment by janinko** [comment]
I don't know any, what about @jbartece @matejonnet ?

**Pull request merged**
