### PR TITLE
Ncl 1033 

### PR DESCRIPTION
**Pull request by pslegr**

### CODE REVIEW

**Comment by pslegr** [comment]
retest this please

**Comment by pslegr** [comment]
retest this please

**Comment by pslegr** [comment]
retest this please

**Comment by alexcreasy** [comment]
I'm reverting this PR as it's causing some build problems, @pslegr sorry, I've sent you an email explaining.

**Comment by pslegr** [comment]
How's that possible all the tests passing ? and you need to revert this one ? Please make a summary list of 1. What is the problem 2. What it has caused 3. Where did that occur. Add some more test so it is obvious, where the problem is. You've reverted, but without any follow up information from your side. I am blocked and can not take any consequent actions. Thanks !

**Pull request merged**
