### PR TITLE
[NCL-6008] - Milestone Brewpush not showing brew-url

### PR DESCRIPTION
**Pull request by vibe13**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Review by alexcreasy — CHANGES_REQUESTED** [review]
So I'd change this slightly, I think just having each build in the main list will be a bit confusing. Also I'm pretty sure having a <div> tag as a direct child of a <dl> is illegal... (then again most browsers don't care)

Can I suggest that rather than embed them in the main definition list, it might be better to add a new sub heading with a title such as "Pushed Builds" (similar to the "log" sub heading) and then have a table, doing an ng-repeat on each row, with a column for status, id, brewBuildId and brew Build URL ?

**Comment by alexcreasy** [comment]
Ok so I felt a bit nerdy and looked up the div within a dl issue... the rules are:

Either: Zero or more groups each consisting of one or more <dt> elements followed by one or more <dd> elements, optionally intermixed with <script> and <template> elements.
Or: One or more <div> elements, optionally intermixed with <script> and <template> elements.

So, my interpretation is you can either have dt tags or div tags? Either way it's complicated... :)

**Comment by vibe13** [comment]
@alexcreasy Thanks for the review and the suggestion, much appreciated!! Just pushed another attempt :-D thanks!

**Review by alexcreasy — APPROVED** [review]
Looks good to me!

**Comment by vibe13** [comment]
thanks Alex!!

**Pull request merged**
