### PR TITLE
NCL-4435

### PR DESCRIPTION
**Pull request by alexcreasy**
### Checklist:

* [x] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by alexcreasy** [comment]
@thescouser89 this wasn't ready to go, it's broken :( I should have put some note on the PR that I was holding off as everything was ticked and it looked ready to go. I had to context switch onto sprint tasks and was coming back to this after they were done.

This probably is a good point we need to figure out, what do we do with PRs that are opened for people to discuss and collaborate on but aren't quite ready to go? We don't want them piling up, but likewise, if they are going to run a long time and aren't ready to merge, do we close them? Do we tag them as not ready or something? 

Ultimately the lack of adequate tests is the real culprit here I suppose, but beyond that, is there some process we can adopt?

Let's not revert this as it breaks nothing else, I'll try and come up with a minimum fix today.

**Comment by matedo1** [comment]
I think there could be two solutions, use title prefix like [don't merge] or there is draft pull request feature https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by thescouser89** [comment]
Draft pull request works!

**Comment by alexcreasy** [comment]
I think draft pull requests seem like exactly what we need 👍

**Pull request merged**
