### PR TITLE
Add a hidden field in BuildEnvironment so to hide them from the combo…

### PR DESCRIPTION
**Pull request by vibe13**
…box; do not return hidden environment to non system-users via REST

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by vibe13** [comment]
@thescouser89 could you please take a look? Wdyt? Thanks!

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by thescouser89** [comment]
Sorry for late review. LGTM!

**Pull request merged**
