### PR TITLE
[v1.8][NCL-5107] Add more user logs about promotion progress

### PR DESCRIPTION
**Pull request by thescouser89**
This PR adds logs on the various phases inside build promotion, as well as the time it took.

It also adds additional `BuildExecutionStatus` to let the user know via websocket in which build promotion phase we are currently in.

Note that the changes to `BuildExecutionStatus` are *not* in the 2.0 branch since we are revamping the way logs / notifications reaches the user.

### Checklist:

* [x] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
ncl-5107

@pkocandr  @matejonnet  What the live logs look like. Let me know what you think!

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
@pkocandr @matejonnet I'm also wondering if I should add timestamp (UTC) in the notification. WDYT?

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by pkocandr** [comment]
Regarding the timestamps - it would make sense if we have them in all status changes.

**Comment by thescouser89** [comment]
Aww conflicts :(

Will close and recreate a new one

**Pull request closed without merging**
