### PR TITLE
Implementation of artifacts view of a Build Configuration Set

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by slaskawi** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Pull request merged**
