### PR TITLE
[NCL-4948] Consolidate rest entity names

### PR DESCRIPTION
**Pull request by janinko**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by michalovjan** [comment]
@matedo1 Just a heads up! :) After this is merged, for filtering SCMRepository inside BConfig you will have to use "scmRepository" as a RSQL key and not "repository".

**Comment by matedo1** [comment]
Thanks @michalovjan I created new jira for it

**Pull request merged**
