### PR TITLE
NCL-805 - Create a Product Milestone in web UI.

### PR DESCRIPTION
**Pull request by jsenko**

### CODE REVIEW

**Comment by slaskawi** [comment]
add to whitelist

**Comment by slaskawi** [comment]
test this please

**Comment by jsenko** [comment]
@alexcreasy hi could you check this pls?

**Comment by vibe13** [comment]
@jsenko Looks good to me, please fix:
[INFO] app/product/product-controllers.js
[INFO]   line 105  col 8  Missing semicolon.
so that CI is happy. Thanks!

**Pull request merged**
