### PR TITLE
Post demo ui

### PR DESCRIPTION
**Pull request by alexcreasy**
Merge UI with grunt / maven-frontend workflow

### CODE REVIEW

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
Phew!

**Pull request merged**
