### PR TITLE
[NCL-533] Improve confirmation panels

### PR DESCRIPTION
**Pull request by thescouser89**
This is done by integrating sweetalert with PNC.

delete_form

### CODE REVIEW

**Comment by thescouser89** [comment]
@emmettu This might break the PNC end-to-end testing. :smiley:

**Comment by slaskawi** [comment]
Wow, looks awesome. @alexcreasy @vibe13 WDYT?

**Comment by vibe13** [comment]
They look very good, like them a lot.

**Comment by alexcreasy** [comment]
Thanks for this @thescouser89 - I think this is much better than what we currently have. 

Personally I think it would be better to have something based on the patternfly modal widget [see: https://www.patternfly.org/widgets/#modal]. Although I realise this will probably require more coding out of the box, sticking with patternfly widgets whenever possible is recommended to: 

1) Give a consistent JBoss look and feel to the project
2) Use UX patterns that have undergone user testing by our UX team 
3) If the UX team refresh the patternfly style in the future, we only have to upgrade the library.

That said, I'd be happy to merge this for now, with one reservation. I think the "Done" screen is a little redundant. We have the existing patternfly notification to let you know the action was successful and more importantly it requires the user to make another unnecessary click. I think the unnecessary extra click will be a bit frustrating for users.

Does anyone else have any thoughts on this?

**Comment by thescouser89** [comment]
@alexcreasy I can remove the "Done" screen. I agree with your point that it's a little bit redundant.

**Comment by thescouser89** [comment]
PR  #619 uses modals instead of sweetalert

**Pull request closed without merging**
