### PR TITLE
[NCL-4186] add buildContentIds for failed build for consistency and make script that restores bCIds

### PR DESCRIPTION
**Pull request by michalovjan**
### Checklist:

* [NCL-4186] changed behaviour from saving buildContentId only on succesful build to saving everytime 
* [NCL-4186] added script that is able restore non saved buildContentIds from buildLogs

### CODE REVIEW

**Comment by thescouser89** [comment]
Is that a query that needs to be run in the 1.4 -> 2.0 migration?
It's missing a semi-colon at the end.

I'm not familiar with the changes required so won't comment on the Java code.

**Comment by michalovjan** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by michalovjan** [comment]
@thescouser89 With @pkocandr and @jbartece we've come to a conclusion that this script should be released in 1.4.2, is the file name right? I've also added license and semicolon.

**Comment by thescouser89** [comment]
It's correct! Sorry for slow reply

**Pull request merged**
