### PR TITLE
Changed path of footer.htm and replacement of tokens

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by vibe13** [comment]
@rnc mind to review?

**Comment by rnc** [comment]
Looks ok ; is there a reason you haven't named it footer.tmpl.html like the other template files?

**Comment by vibe13** [comment]
@rnc actually no reason, renamed

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
@rnc good to merge?

**Comment by rnc** [comment]
@vibe13 fine by me.

**Pull request merged**
