### PR TITLE
NCL-777 & NCL-824

### PR DESCRIPTION
**Pull request by alexcreasy**
* NCL-777 - Pnc UI web - properly handle the 401 & 403 responses from REST endpoints
  * NCL-824 - UI flicker is somtimes noticeable when navigating (when authentication is enabled)

### CODE REVIEW

**Comment by alexcreasy** [comment]
@pslegr if you're happy this implements NCL-777 I'll merge this

**Comment by pslegr** [comment]
I will check this one

**Comment by pslegr** [comment]
Alex, the functionality for authorized/unauthorized users works as expected. So once the user in not authorized the err msg is thrown, however it is not the: "errTitle = '403: Forbidden';
+          errMsg = 'You do not have permision to access this resource';"  but the "standard one". Please retest at your place, with "pnc-admin" & "testone" users... the "testone" user has the same passwd as pnc-admin, but does have only "user" role and should get always 403 for anything else except "GET" requests

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
@pslegr could you review this update? For form submissions where the user does not have permission a popup stating the user does not have permission is triggered.

**Comment by pslegr** [comment]
Ok, making review

**Comment by pslegr** [comment]
Looks good ! Go ahead and merge ! I will close the related issue afterwards

**Comment by alexcreasy** [comment]
Great thanks, merging

**Pull request merged**
