### PR TITLE
NCL-1354- Improved names for cloned BuildConfigurations - CLEANED

### PR DESCRIPTION
**Pull request by vibe13**
@alexcreasy @matejonnet this should be cherry picked to 0.7 branch also

### CODE REVIEW

**Comment by vibe13** [comment]
test this please

**Comment by vibe13** [comment]
test this please

**Comment by vibe13** [comment]
@alexcreasy  any comments on this?

**Comment by alexcreasy** [comment]
:+1: this is a neater cloned BC prefix than we had before.

**Pull request merged**
