### PR TITLE
Ncl 567

### PR DESCRIPTION
**Pull request by slaskawi**
Key features:
* Refactored core's event, now it contains additional data
* Introduced CDI event broadcast adapter, which forwards all Status Notification to CDI event bus
* Added main event type to SPI package
* Introduced a small adapter for tests, just to show how it will be used in REST interface.

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @matejonnet @jbartece @mareknovotny !

Could you please do me a code review for this?

Thanks!

**Comment by slaskawi** [comment]
@matejonnet @jbartece @mareknovotny Going once :D

**Comment by matejonnet** [comment]
Merge it.

**Comment by slaskawi** [comment]
aye Captain! Merging...

**Pull request merged**
