### PR TITLE
NCL-1956 Use separate deployment URL to deploy directly to hosted repo

### PR DESCRIPTION
**Pull request by pkocandr**

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by jdcasey** [comment]
@pkocandr +1 from me, but do we know what needs to change in terms of how the settings.xml gets generated? It may need to be updated...?

**Comment by pkocandr** [comment]
I checked that before and this should be the only necessary change being made, because the settings.xml template already contains altDeploymentRepsoitory with value "aprox::default::${AProxDeployUrl}". The placeholder is replaced by the getDeployUrl() result.

**Pull request merged**
