### PR TITLE
Add internal DTOs

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
Yeah, I'm not totally sure about the any of the internal DTOs and was expecting that there are going to be changes to them.

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by matejonnet** [comment]
What is the reason for the internal DTO ?

**Comment by janinko** [comment]
@matejonnet What do you mean? These are used by the /build-task endpoints IIRC.

**Comment by janinko** [comment]
@matejonnet What do you mean? These are used by the /build-task endpoints IIRC.

**Comment by janinko** [comment]
@matejonnet What do you mean? These are used by the /build-task endpoints IIRC.

**Comment by janinko** [comment]
@matejonnet These are needed by the /build-tasks endpoint AFAIK.

**Pull request merged**
