### PR TITLE
[NCL-5622] Throw nice error if PV already exists

### PR DESCRIPTION
**Pull request by thescouser89**
Where PV  = prodcut version

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by jbartece** [comment]
A test would be nice

**Comment by thescouser89** [comment]
ack

**Comment by thescouser89** [comment]
Test added

**Comment by thescouser89** [comment]
From CLI:

```
➜  pnc git:(ncl-5622) bacon pnc product-version create --product-id 100 1.0 
Enter your password: 
[ERROR] - Something wrong happened: Product version with version 1.0 already exists
➜  pnc git:(ncl-5622) 

```

**Pull request merged**
