### PR TITLE
Add some uniqueness constraints on the model

### PR DESCRIPTION
**Pull request by thescouser89**
## Uniqueness on `name`:
* BuildConfiguration.java
* BuildConfigurationSet.java
* Product.java
* Project.java

## Uniqueness on `version` and `product_id`:
* ProductVersion.java

## Uniqueness on `version` and `productVersion_id`:
* ProductMilestone.java
* ProductRelease.java

## Uniqueness on `username` and/or `email`:
* User.java

Note: Right now the web-ui will fail to capture those uniqueness
violations that might occur while creating any of the models above.
Future work will go on making the web-ui aware of any model errors.

### CODE REVIEW

**Comment by pgier** [comment]
Can you create a jira for this?

**Comment by thescouser89** [comment]
@pgier will do!

**Comment by thescouser89** [comment]
NCL-1201 is the JIRA created for this issue.

**Comment by pgier** [comment]
Merged in PR #525

**Pull request closed without merging**
