### PR TITLE
NC-1839 UI Part

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
