### PR TITLE
[NCL-5261] Add constraint for REST page size (max 200)

### PR DESCRIPTION
**Pull request by janinko**
### Checklist:

* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by janinko** [comment]
@matedo1 I added mapping of the validation to the format from our REST Guidelines. Couldn't do much magic with it, but hope it's ok:
```
{
  "errorType": "VALIDATION",
  "errorMessage": "Constraint violation: getAll.arg0.pageSize: musí být menší než nebo rovno 200, getAll.arg0.pageIndex: must be greater than or equal to 0",
  "details": {
    "validation": [
      {
        "attribute": "getAll.arg0.pageSize",
        "messages": [
          "musí být menší než nebo rovno 200"
        ],
        "value": 201
      },
      {
        "attribute": "getAll.arg0.pageIndex",
        "messages": [
          "must be greater than or equal to 0"
        ],
        "value": -1
      }
    ]
  }
}
```

**Comment by matedo1** [comment]
@janinko sounds good, just make sure english is used in all places

**Comment by janinko** [comment]
> @janinko sounds good, just make sure english is used in all places

it's automatically generated and I have czech locale

**Comment by janinko** [comment]
retest this please

**Pull request merged**
