### PR TITLE
Ncl 1462 - Improve network calls and polish UI

### PR DESCRIPTION
**Pull request by vibe13**
There are many unnecessary and duplicated network calls when loading the pages across Product Details, ProductVersions, BuildConfigurations, BuildConfigurationSets, mainly to retrieve Milestone, Releases, ProducVersions, Projects, Users, BuildConfigurations.
Some changes should be done:

* enrich where necessary the response of the endpoints, to have fully serialized objects and not just the ids, to avoid further network calls
* polish the UI, as many refactorings, that introduced angular directives, did not polish the network calls from the controllers, leading to many duplicated endpoints calls

### CODE REVIEW

**Comment by alexcreasy** [comment]
@vibe13 I haven't had a chance to test this yet, but just looking through the code, we've been crying out for these improvements! I'll give this a test first thing tomorrow and get it merged.

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
@alexcreasy thanks, I have completed some optimizations and (hopefully, now I am going to sleep) fixed the integration tests that were failing.

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
umpf, finally tests passed :-)

**Comment by slaskawi** [comment]
:+1:

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
@matejonnet @sbunciak  hi guys, I would like to merge this as it is pending for quite some time. This will need some changes in DA, as previously discussed. wdyt?

**Comment by vibe13** [comment]
retest this please

**Pull request merged**
