### PR TITLE
[NCL-427] Remove patches URL from build configuration

### PR DESCRIPTION
**Pull request by pgier**
JBoss product builds under project Newcastle must not use external patches to a build.
All sources should be kept in a single scm repository.

### CODE REVIEW

**Comment by slaskawi** [comment]
+1 waiting for others to comments and integrating at the end of the day

**Comment by vibe13** [comment]
@pgier Hi Paul, some more files should be changed:
* pnc-ui/app/views/configuration_add.html (remove LN 89-94)
* pnc-ui/app/views/configurations.html (remove LN 75)
* pnc-ui/app/scripts/pnc-configurations.js (remove LN 69; LN 259; LN 265)

**Comment by pgier** [comment]
@vibe13 Thanks!  I have pushed an updated commit.

**Comment by slaskawi** [comment]
@vibe13 @pgier Should I integrate this one?

**Comment by vibe13** [comment]
@slaskawi No not yet, I believe it's freezed waiting for some more consensus

**Comment by slaskawi** [comment]
@vibe13 @pgier How about this PR? Are going to work on this or should we just close it?

**Comment by slaskawi** [comment]
Closing...

Please reopen and rebase it if needed.

**Pull request closed without merging**
