### PR TITLE
Result detail

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Test this please

**Comment by alexcreasy** [comment]
*Slips jdg-bot £20* Make it snappy old friend!

**Comment by vibe13** [comment]
@alexcreasy opened https://github.com/project-ncl/pnc/pull/201 with some fixes and minor improvements

**Comment by slaskawi** [comment]
retest this please

**Comment by slaskawi** [comment]
jdg-bot took the cash and got drunk...

**Comment by jbartece** [comment]
retest this please

**Comment by vibe13** [comment]
Closing as this was included in https://github.com/project-ncl/pnc/pull/209

**Pull request closed without merging**
