### PR TITLE
[NCL-4007] Button for BuildGroup canceling

### PR DESCRIPTION
**Pull request by michalovjan**

### CODE REVIEW

**Comment by matedo1** [comment]
retest this please

**Comment by matedo1** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by matedo1** [comment]
retest this please

**Pull request merged**
