### PR TITLE
NCL-935 

### PR DESCRIPTION
**Pull request by thauser**
Modifies the ProductEndpoint and ProductVersionEndpoint as discussed.

ProductEndpoint:
GET /{id}/product-versions - returns a list of all versions for product with id {id}
POST /{id}/product-versions - creates a new product version associated with this product

ProductVersionEndpoint:
Changed base path to /product-versions
GET / - returns ALL product-versions, regardless of product association
GET /{id} - returns a specific product version with id {id}

### CODE REVIEW

**Comment by thauser** [comment]
test this please

**Comment by slaskawi** [comment]
test this please

**Comment by thauser** [comment]
test this please

**Comment by slaskawi** [comment]
add to whitelist

**Comment by slaskawi** [comment]
test this please

**Comment by thauser** [comment]
test this please

**Comment by slaskawi** [comment]
retest this please

**Pull request merged**
