### PR TITLE
[master] NCL-4051 Increase size of build script widget in BC edit view

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this PLEASE

**Comment by alexcreasy** [comment]
PASS THIS OR I WILL DESTROY YOU

**Comment by alexcreasy** [comment]
/me makes note to go fix the intermittent test suite failures on Tuesday.

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
