### PR TITLE
Update to EAP 7.

### PR DESCRIPTION
**Pull request by matejonnet**
This is a combination of 26 commits:

Updated dependencies and fix model and datastore sequence gen.

Reconfigure container tests to use EAP7.

Update arquilian set-up.

Fix springframewor versions.

Explicitelly define JPA query in Spring repository.

Fix build driver test to use system tmp path.

Use maven-war-plugin version from parent pom.

Force infinispan version in repository manager tests.

Fix intergarion tests set-up.

Use EAP7 security domain mapping name.

Fix demo data initialization.

Integration tests running.

Organize dependencies.

Fix BCSet integration test - WIP.

Clean UP.

Clean UP.

Align to EAP 7.0.7 libs.

Ignore outdated BuildRecord tests.

Fix WebSocketsNotificationTest for some reason @before does not work properly.

Fix saving artifacts with BuildRecord.

Load BCs from DB.

Ignore RepositoryCreation test.

Run WS Notification tests in-sequence.

Do not compare dependent fields.

Tests config: Increase xmx and reduce logging.

Clean up POMs.

Clean up.

Remove non required settings from jboss-web.xml.

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
@matejonnet Could you cherry-pick the commit from  #1678 once it is merged? This will help to build this PR

**Comment by matejonnet** [comment]
@thescouser89 rebased on latest master

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
