### PR TITLE
Refactored UI dir. structure to better reflect state and URL hierarchy.

### PR DESCRIPTION
**Pull request by jsenko**
@alexcreasy, @vibe13 can you take a look?
The new dir. structure follows state hierarchy and is IMHO much more clear & understandable. In addition, state and controller definitions have their own files so they are not crammed together.

### CODE REVIEW

**Comment by alexcreasy** [comment]
Hi Jakub, 

I have only had time to take a quick look at this, there are some ideas here I like though that will make the codebase easier to navigate. This will have to go through some rounds of discussion and possible changes though before we can look to merge it. It is certainly too big a change to go in until after 0.5 release branch is cut, so please don't merge this for now.

**Comment by jsenko** [comment]
retest this please

**Comment by slaskawi** [comment]
Probably needs rebase

**Comment by alexcreasy** [comment]
I think we should close this for now, it's been sitting here a long time and we need to come to an agreement about what conventions we should follow before undertaking a wholesale refactor.

**Comment by slaskawi** [comment]
Ok, no problem. Closing...

**Pull request closed without merging**
