### PR TITLE
Fixes NCL-3302 / NCL-3303 v1.2

### PR DESCRIPTION
**Pull request by alexcreasy**
- NCL-3302 Wizard is still navigable after completion
  - NCL-3303 Wizard next button incorrectly labelled on completion

(cherry picked from commit 1f9f8c04ab048cfe70f9119fb4f0b0be56cc0b5c)
Signed-off-by: Alex Creasy <acreasy@redhat.com>

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
