### PR TITLE
Ncl 843

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by vibe13** [comment]
@matejonnet please take a look and review.

Things to note:
1) BuildConfigSetRecord and BuildRecord have now a Sequence generator for the ID
2) SequenceHandlerRepository has a method (https://github.com/project-ncl/pnc/pull/368/files#diff-22c5fd21ae3c87d8271e474090943927R35) to retrieve the nextVal() from any sequence specified, which triggers the underlying sequence in the correct database (conversion for the different Dialects is still handled by Hibernate)
3) The tricky part was to use a Sequence to retrieve the nextVal() of a BuildRecord, while still having the possibility to insert a BuildRecord with a specified ID. This is not possible if done via classic Hibernate (that would trigger the sequence at any insertion). But is possible if done via nativeSQL / preparedStatement: https://github.com/project-ncl/pnc/pull/368/files#diff-22c5fd21ae3c87d8271e474090943927R70
4) The creation of a NativeQuery in SpringData has not been possible, as there were Null checks (i.e. https://github.com/project-ncl/pnc/pull/368/files#diff-22c5fd21ae3c87d8271e474090943927R92) that could not be done automatically
5) To be able to insert a BuildLog (declared as a String @Lob), an additional annotation is required: https://github.com/project-ncl/pnc/pull/368/files#diff-87c8deb9f9282485381829f38bbaaec7R96

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
@matejonnet please review

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
CI failing because No space left on device

**Comment by vibe13** [comment]
retest this please

**Comment by matejonnet** [comment]
Looks great!

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
retest this please

**Pull request merged**
