### PR TITLE
[NCL-434] Remove product_version_project and add build_record_set

### PR DESCRIPTION
**Pull request by pgier**
This changes the db model and rest interface to remove the existing
product_version_project entity and add the new entity build_record_set

### CODE REVIEW

**Comment by jbartece** [comment]
It looks that master was broken for longer time. Please rebase it to the current upstream/master

**Comment by slaskawi** [comment]
retest this please

**Comment by pgier** [comment]
retest this please

**Comment by slaskawi** [comment]
retest this please

**Comment by pgier** [comment]
retest this please

**Pull request merged**
