### PR TITLE
[v1.8][NCL-4611] added special case for milestone version pattern matching

### PR DESCRIPTION
**Pull request by michalovjan**
### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
Should this target v1.6 instead now?

**Comment by michalovjan** [comment]
I think v1.7.

**Comment by thescouser89** [comment]
retest this please

**Comment by michalovjan** [comment]
target changed to 1.8

**Pull request merged**
