### PR TITLE
[NCL-7381] get rid of CVEs 

### PR DESCRIPTION
**Pull request by michalovjan**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

Summary (I may have missed some dependency changes):

changed: 
rh-sso-adapter: 7.4.0.GA -> 7.4.8.GA
keycloak: 9.0.3.redhat-00002 -> 9.0.14.redhat-00001
byte-buddy: 1.10.18 -> 1.10.20
hsqldb: 2.4.1-jdk8 -> 2.7.1-jdk11
spring-data-jpa 1.11.23.RELEASE -> 2.3.9.RELEASE
spring-data-commons 1.13.23.RELEASE -> 2.3.9.RELEASE
fluent-hc: 4.5.4-> 4.5.14
vertx: 3.8.5 -> 3.9.14
swagger2: 2.1.4 -> 2.2.8

gav-changed:
com.github.fge:json-patch:1.9 -> com.github.java-json-tools:1.13

removed:
jbpm-test: 6.2.0
jackson-xc
jcip-annotations: 1.0.0.redhat-8
jsch:
jsoup:1.8.3
packageurl-java:
awaitility: 4.2.0
snakeyaml: 1.27
org.glassfish.web:javax.el: 2.2.6
net.joday:failsafe: 2.4.0
io.fabric8:openshift-client: 5.0.1
indy-model-core-java
indy-embedder
indy-client-core-java
indy-text-fixtures-core
slf4j-log4j12: 1.7.30
org.json:json

- extracted versions into properties
- organized properties to seperate test-only dependencies
- added a CVE dependency check
- general cleanup
- spring API adjustments

### CODE REVIEW

**Comment by michalovjan** [comment]
retest me please

**Comment by michalovjan** [comment]
retest me please

**Review by matejonnet — APPROVED** [review]

**Comment by michalovjan** [comment]
retest me please

**Comment by michalovjan** [comment]
retest this please

**Review by thescouser89 — APPROVED** [review]

**Pull request merged**
