### PR TITLE
[NCL-782] Enabling authentication causes UI malfunction

### PR DESCRIPTION
**Pull request by alexcreasy**

### CODE REVIEW

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
@rnc @vibe13 would you mind reviewing this?

There are a few things to note from this PR - the following should (hopefully) now be true.

1) building all of PNC with -Dauth=true and then accessing the UI requires you to login, and functions correctly after successful login
2) building PNC with -Dauth=false and then accessing the UI allows correct function of UI without logging in.
3) Running `grunt serve --enable-auth=true` from pnc-ui folder allows using live-reload server with authentication.
4) Running `grunt serve` allows using live-reload server without authentication.

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
retest this please

**Comment by alexcreasy** [comment]
@vibe13 when you have some time, if you could check this. The issue with authentication disabled should now be fixed.

**Comment by vibe13** [comment]
retest this please

**Comment by vibe13** [comment]
@alexcreasy Did the following tests:
1) mvn clean install --> ok auth disabled
2) grunt serve --> ok works against non-authenticated installation
3) mvn clean install -Dauth=true -Dauth.eap.home=<EAP_HOME> --> ok auth enabled
4) grunt serve --enable-auth=true --> ok works against authenticated-enabled installation

Will fire CI, then merge

**Pull request merged**
