### PR TITLE
[v1.4] Update HSQLDB version to 2.4.1

### PR DESCRIPTION
**Pull request by thescouser89**

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by alexcreasy** [comment]
@thescouser89 will this fix the problems with CI? ;)

**Comment by thescouser89** [comment]
@alexcreasy Unfortunately not :( I merged the change to a PR and it did nothing

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
