### PR TITLE
[v1.4] NCL-4051 Increase size of build script widget in BC edit view

### PR DESCRIPTION
**Pull request by alexcreasy**
(cherry picked from commit d141ef423504d54c398562f41d681f5b9c1286bd)
Signed-off-by: Alex Creasy <acreasy@redhat.com>

### CODE REVIEW

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by alexcreasy** [comment]
@thescouser89 thanks Dustin 👍

**Pull request merged**
