### PR TITLE
Ncl 1340

### PR DESCRIPTION
**Pull request by jsenko**
Started solving this by caching the pages, and extended the caching to all DAO methods.

### CODE REVIEW

**Comment by jsenko** [comment]
Made a mistake during rebase (last two commits are exchanged) but it does not affect the result.

**Comment by matejonnet** [comment]
It would be nice to have some tests for this new functionalities.

**Comment by jsenko** [comment]
retest this please

**Comment by alexcreasy** [comment]
Sorry Jakub, due to how much of the codebase this touches it will need further review and probably need to be broken down into smaller PRs before it can be merged. I'll look into this again in the new year.

**Pull request closed without merging**
