### PR TITLE
[NCL-5922] Remove wrong check when deleting builds from indy

### PR DESCRIPTION
**Pull request by janinko**
The check was wrong because it checked wrong repo in the group. We
can remove the check as the TODO said because all builds are now
in consolidated repository.

### Checklist:

* [x] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Review by pkocandr — APPROVED** [review]
LGTM. Thanks for finding this!

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Pull request merged**
