### PR TITLE
NCL-1094 use correct Endpoint to add version to product

### PR DESCRIPTION
**Pull request by ahmedlawi92**

### CODE REVIEW

**Comment by ahmedlawi92** [comment]
test this please

**Comment by slaskawi** [comment]
@alexcreasy Could you please take a look at it?

**Comment by alexcreasy** [comment]
I'm not sure this REST endpoint for creating a ProductVersion is consistent with our existing REST endpoints.

To create a BuildConfiguration we use `POST /build-configurations` we don't use `POST /projects/addBuildConfiguration`.

It also leads to non-idiomatic code. For example in the UI you are creating a new product-version by calling `new PncRestClient.Product()` rather than `new PncRestClient.Version()`.

I'm actually deprecating the PncRestClient gradually and the underlying Product and ProductVersion models will be invoked directly, I can see it getting mroe confusing at this point.

@ahmedlawi92 @slaskawi - what do you think?

**Comment by ahmedlawi92** [comment]
@alexcreasy Hey, I could see the creation being moved to the ProductVersionEndpoint, but I think that the creation of the ProductVersion and its being added the corresponding Product should be coupled together.

So something along the lines of POST /product-versions where you provide the ProductVersion details and the Product object.

I don't think it should be separated into two different operations such as POST /product-versions where you create the ProductVersion and POST /products/:id/product-versions to add the created ProductVersion to the Product.

**Comment by alexcreasy** [comment]
@ahmedlawi92 Yes I completely agree, I was thinking `POST /product-versions` which should reject any request that doesn't contain a valid `productId` field. This is how the `/build-configurations` endpoints behave with regards to their parent Project.

**Comment by slaskawi** [comment]
Backend code looks nice! Small question - do we need any integration tests around this functionality? Or this is not critical and we are ok without them?

**Comment by slaskawi** [comment]
retest this please

**Comment by ahmedlawi92** [comment]
@slaskawi Hey, I actually just updated the integration tests to test the addition of the product-version from the new endpoint. I'm not sure if its critical but there were already tests in place for the old endpoint. I don't think it really hurts to have these tests there.

**Comment by slaskawi** [comment]
@ahmedlawi92 Ohh yes, sorry - you're absolutely right. :+1: from me.

**Pull request merged**
