### PR TITLE
NCL-5038 UI support for PATCH methods

### PR DESCRIPTION
**Pull request by alexcreasy**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by alexcreasy** [comment]
@matedo1 you may want to take a look at this. 

I'm going to merge as soon as it passes CI so I can rebase the group-config refactor code on top of this. I thought it was important to extract this code out into its own JIRA / PR for proper record keeping.

**Comment by alexcreasy** [comment]
Retest this please

**Comment by alexcreasy** [comment]
Retest this please

**Comment by matedo1** [comment]
> @matedo1 you may want to take a look at this.
> 
> I'm going to merge as soon as it passes CI so I can rebase the group-config refactor code on top of this. I thought it was important to extract this code out into its own JIRA / PR for proper record keeping.

Thanks for letting me know, I will look at this

**Pull request merged**
