### PR TITLE
[NCL-3304] Create BC button disabled when user not logged in

### PR DESCRIPTION
**Pull request by thescouser89**

### CODE REVIEW

**Comment by thescouser89** [comment]
I'm not sure what's up with the app.html changes... if it's expected or no. @alexcreasy ?

**Comment by thescouser89** [comment]
ncl-3304

**Comment by matedo1** [comment]
@thescouser89 Thanks for this change! It would be a little bit cleaner to commit app.html changes separately, but anyway it's not a big problem as I also wanted to push them soon.

**Comment by alexcreasy** [comment]
+1 thanks Dustin! re: the random crap in index.html, ideally we would only include dependencies in our minified distributions and use a temp index.html for development, I spent 20 minutes trying to implement it once and it wasn't as simple as it should have been so I had to give up.

**Pull request merged**
